# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

init:
  - git config --global core.autocrlf true

environment:
  matrix:
  # node.js
  - nodejs_version: "0.11"
  - nodejs_version: "0.12"
  # io.js
  - nodejs_version: "1.0"
  allow_failures:
    - nodejs_version: "0.11"

install:
  - ps: Install-Product node $env:nodejs_version

install:
  - npm install

build: off

test_script:
  - node --version && npm --version

matrix:
  fast_finish: true
