# http://www.appveyor.com/docs/appveyor-yml

environment:
  nodejs_version: "0.12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g gulp
  - npm install

test_script:
  - node --version
  - npm --version

build: off
